### PR TITLE
[WIP] SAMZA-1938: Support use cases to run multiple sql statements in one Samza job

### PR DESCRIPTION
**Pull request by weiqingy**
## What changes were proposed in this pull request?

This PR is to support the following user scenarios:
1. support users to run multiple Sql statements in the same job.
- sql1 = "Insert into testavro.simpleOutputTopic select * from testavro.SIMPLE1";
-  sql2 = "Insert into testavro.SIMPLE3 select * from testavro.SIMPLE2";

2. Support fan-out use case. For example, 
- sql1 = "Insert into testavro.SIMPLE2 select * from testavro.SIMPLE1";
- sql2 = "Insert into testavro.SIMPLE3 select * from testavro.SIMPLE1";

3. Support fan-in use case. For example,
- sql1 = "Insert into testavro.simpleOutputTopic select * from testavro.SIMPLE2";
- sql2 = "Insert into testavro.simpleOutputTopic select * from testavro.SIMPLE1";

This PR make the information about SystemDescriptors,  MessageStream of input sources and OutputStreams stored in QueryTranslator because those information belongs to the job, and each job has only one QueryTranslator object.

## How was this patch tested?
1. Add unit tests
2. Testing in Samza SQL shell.

### CODE REVIEW

**Comment by weiqingy** [comment]
Hi @atoomula, Could you pls help to review this? Thanks.

**Comment by weiqingy** [comment]
It seems the current master branch is broken. Build fail. 
```
/Users/wiyang/Workingspace/apacherelease/samza/samza-test/src/test/java/org/apache/samza/test/framework/FaultInjectionTest.java:57: error: cannot find symbol
    configs.put(JobCoordinatorConfig.JOB_COORDINATION_UTILS_FACTORY, "org.apache.samza.zk.ZkCoordinationUtilsFactory");
                                    ^
  symbol:   variable JOB_COORDINATION_UTILS_FACTORY
  location: class JobCoordinatorConfig
```

Need to wait for the fix to master branch..

**Comment by weiqingy** [comment]
This PR includes the code changes of https://github.com/apache/samza/pull/691. After https://github.com/apache/samza/pull/691 is merged, I will update this PR to remove those code changes.

**Comment by vjagadish1989** [comment]
@weiqingy : is master still broken after the rebase?

**Comment by weiqingy** [comment]
Just rebased the code changes from master, but got the following error:

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/apache/samza.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:888)
```

This error is not related to this PR, so re-trigger the build.

**Comment by weiqingy** [comment]
Thanks, @vjagadish1989 After rebasing, the build passed. But there an error from Jenkins:

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/apache/samza.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:888)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1155)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
	at hudson.scm.SCM.checkout(SCM.java:504)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1794)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/apache/samza.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: error: Could not read 02192052f44a27bd3cdbb3dee1eff94f416cf666
error: Could not read 32c92828eaff98f4c2e6691533ece9f502ef1f98
```
Any thoughts about this?

**Comment by weiqingy** [comment]
There are too much conflicts. I'll create another PR for this.
